# -*- coding: utf-8 -*-
"""Análise_Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcP0AFqY0iz6RKn7BZ-JsGiPCB63g8lN
"""

import pandas as pd
import plotly.express as px

tabela = pd.read_csv("marketing_campaign.csv", sep= ';')
display(tabela)

tabela = tabela.dropna()
display(tabela)
# display(tabela.head(15))
display(tabela.describe().round(1))
# display(tabela.shape)
tabela["Education"] = tabela["Education"].str.strip()
tabela["Education"] = tabela["Education"].str.title()
display(tabela.info())
tabela = tabela.drop_duplicates(subset=["ID"])

tabela_filtrada = tabela[tabela["Year_Birth"] > 1930]

grafico = px.histogram(tabela_filtrada, x="Year_Birth")
grafico.show()

